"use client";

import React, { useState } from "react";
import Link from "next/link";
import { FileText, ShieldCheck, CheckCircle2, ArrowLeft, Clock, CreditCard, Award } from "lucide-react";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { BookingModal } from "@/components/booking-modal";

export default function TermsOfServicePage() {
  const [isBookingOpen, setIsBookingOpen] = useState(false);

  const sections = [
    {
      id: "agreement",
      title: "1. Acceptance of Terms & Practice Scope",
      content: `By accessing our website, booking an appointment, using our electronic portal, or receiving dental services at any SmileCare Dental Practice Network branch clinic (Toronto Central, Vancouver West, Calgary Downtown, Ottawa Parliament, Mississauga Medical, Montreal Downtown), you agree to be bound by these Terms of Service. These terms constitute a legally binding agreement between you ("Patient", "User") and SmileCare Practice Management Inc.`,
    },
    {
      id: "appointments-cancellation",
      title: "2. Appointment Booking & 24-Hour Cancellation Policy",
      content: `• **Online Booking**: Online appointments booked through our platform are reserved exclusively for you with our licensed DDS specialists.
      \n• **24-Hour Notice Required**: If you need to cancel or reschedule your appointment, you must provide at least 24 hours' notice by phone or through your patient portal.
      \n• **Late Cancellations & Short-Notice Absences**: Failure to provide 24 hours' notice may incur a standard short-notice cancellation fee in accordance with provincial dental association guidelines.`,
    },
    {
      id: "fee-guide-compliance",
      title: "3. Provincial Dental Fee Guide Compliance",
      content: `• **Fee Transparency**: All clinical procedures, diagnostic exams, 3D CBCT scans, cleanings, and restorative treatments are billed in strict compliance with current provincial dental fee guides (ODA in Ontario, BCDA in BC, ADA in Alberta, ACDQ in Quebec).
      \n• **No Surprise Surcharges**: We provide full financial estimates prior to initiating cosmetic or surgical dental treatment.`,
    },
    {
      id: "insurance-co-payments",
      title: "4. Direct Electronic Insurance Billing & Co-Payment Responsibility",
      content: `• **Direct Claims Processing**: We offer direct electronic insurance claim submission to Sun Life Financial, Manulife, Canada Life, Desjardins Insurance, Pacific & Medavie Blue Cross, and CDCP.
      \n• **Patient Responsibility**: While we submit insurance claims on your behalf, you remain ultimately responsible for any non-covered balances, deductibles, co-payments, or claim rejections determined by your insurance policy.`,
    },
    {
      id: "ai-assistant-disclaimer",
      title: "5. Digital Platform & AI Dental Assistant Disclaimer",
      content: `• **Informational Use Only**: Information provided on this website and generated by our DentalFlow AI Assistant is intended strictly for general educational and administrative support.
      \n• **No Medical Diagnosis**: AI responses do not constitute medical diagnosis or prescription. Clinical decisions are made solely during in-person examinations with a licensed Canadian dentist.
      \n• **Medical Traumas**: In case of severe facial swelling, uncontrolled bleeding, or acute trauma, contact emergency services or visit our emergency dental clinic immediately.`,
    },
    {
      id: "governing-law",
      title: "6. Governing Law & Jurisdiction",
      content: `These Terms of Service are governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law principles. Any legal action arising hereunder shall be submitted to the exclusive jurisdiction of the courts of Ontario.`,
    },
  ];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-poppins selection:bg-[#1B5C63] selection:text-white">
      <Navbar onOpenBooking={() => setIsBookingOpen(true)} />

      {/* Header Banner */}
      <div className="bg-[#1B5C63] text-white py-14 sm:py-18 relative overflow-hidden">
        <div className="mx-auto max-w-5xl px-6 lg:px-8 relative z-10 space-y-4">
          <Link
            href="/"
            className="inline-flex items-center space-x-2 text-xs font-semibold text-teal-200 hover:text-white transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to Home</span>
          </Link>
          <div className="flex items-center space-x-3">
            <div className="h-10 w-10 rounded-2xl bg-white/10 flex items-center justify-center border border-white/20">
              <FileText className="h-6 w-6 text-teal-300" />
            </div>
            <span className="text-xs font-mono font-bold tracking-widest text-teal-200 uppercase">
              PATIENT CARE AGREEMENT
            </span>
          </div>
          <h1 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-white">
            Terms of Service
          </h1>
          <p className="font-poppins text-slate-200 text-sm sm:text-base max-w-2xl leading-relaxed">
            Legal terms, appointment booking policies, fee guide adherence, and patient responsibilities across all DentalFlow clinics.
          </p>
        </div>
      </div>

      {/* Content Container */}
      <main className="mx-auto max-w-5xl px-6 lg:px-8 py-12 sm:py-16">
        
        {/* Compliance Badges Bar */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-12">
          <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs flex items-center space-x-3">
            <Clock className="h-5 w-5 text-[#1B5C63] shrink-0" />
            <div>
              <p className="font-serif text-xs font-bold text-slate-900">24-Hour Notice</p>
              <p className="text-[11px] text-slate-500 font-poppins">Standard Cancellation Policy</p>
            </div>
          </div>

          <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs flex items-center space-x-3">
            <Award className="h-5 w-5 text-[#1B5C63] shrink-0" />
            <div>
              <p className="font-serif text-xs font-bold text-slate-900">Fee Guide Compliant</p>
              <p className="text-[11px] text-slate-500 font-poppins">ODA / BCDA / ADA Approved</p>
            </div>
          </div>

          <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs flex items-center space-x-3">
            <CreditCard className="h-5 w-5 text-[#1B5C63] shrink-0" />
            <div>
              <p className="font-serif text-xs font-bold text-slate-900">Direct Electronic Billing</p>
              <p className="text-[11px] text-slate-500 font-poppins">All Major Insurance Carriers</p>
            </div>
          </div>
        </div>

        {/* Policy Sections */}
        <div className="bg-white rounded-3xl border border-slate-200/80 p-8 sm:p-12 shadow-sm space-y-10">
          {sections.map((sec) => (
            <div key={sec.id} className="space-y-3 pb-8 border-b border-slate-100 last:border-0 last:pb-0">
              <h2 className="font-serif text-lg sm:text-xl font-bold text-[#1B5C63] flex items-center space-x-2">
                <span>{sec.title}</span>
              </h2>
              <div className="font-poppins text-xs sm:text-sm text-slate-700 leading-relaxed whitespace-pre-line space-y-2">
                {sec.content}
              </div>
            </div>
          ))}

          {/* Last Updated Footer */}
          <div className="pt-6 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500 font-poppins">
            <span>Last Updated: August 2026</span>
            <span className="font-semibold text-[#1B5C63]">SmileCare Practice Management Inc.</span>
          </div>
        </div>

      </main>

      <Footer />
      <BookingModal isOpen={isBookingOpen} onClose={() => setIsBookingOpen(false)} />
    </div>
  );
}
